# fly.toml app configuration file generated for scm-frontend on 2024-02-01T16:50:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scm-frontend'
primary_region = 'ewr'

[build]
  ignorefile = ".dockerignore"
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
